spring:
  application:
    name: seguros
  data:
    mongodb:
      uri: mongodb://localhost:27017/segurosdb

server:
  port: 8081

resilience4j:
  circuitbreaker:
    instances:
      clienteService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 10
          
management:
  endpoints:
    web:
      exposure:
        include: "*"

cliente:
    url: ${CLIENTES_API_URL:http://localhost:8080}
